import "@/styles/globals.css";

import dynamic from "next/dynamic";
import Header from "@/layout/Header/Header";
import Footer from "@/layout/Footer/";
import LinesScroll from "@/LinesScroll";
import PageTransition from "@/PageTransitionRout";

import { type Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";

const Intro = dynamic(() => import("@/intro"), { ssr: false });
const HoverMouse = dynamic(() => import("@/hoverMous"), { ssr: false });
const GridOverlayFONT = dynamic(() => import("@/GridOverlayFONT"), { ssr: false });

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const hankenGrotesk = Hanken_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  preload: true,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={hankenGrotesk.className}>
        <Intro />
        <LinesScroll>
          <Header />
          <PageTransition>
            <main>{children}</main>
          </PageTransition>
          <Footer />
          {process.env.NODE_ENV === "development" && <GridOverlayFONT />}
        </LinesScroll>
        <HoverMouse />
      </body>
    </html>
  );
}