 import Header from "@/layout/Header/Header";
import Footer from "@/layout/Footer/";
import LinesScroll from "@/LinesScroll";
import GridOverlayFONT from "@/GridOverlayFONT";
import Intro from "@/intro";
import PageTransition from "@/PageTransitionRout";
import HoverMouse from "@/hoverMous";
import "@/styles/globals.css";

import { type Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const hankenGrotesk = Hanken_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={hankenGrotesk.className}>
        <Intro />
        <LinesScroll>
          <Header />
          <PageTransition>
            <main>{children}</main>
          </PageTransition>
          <Footer />
          <GridOverlayFONT />
        </LinesScroll>
        <HoverMouse />
      </body>
    </html>
  );
}